"use client";
import { useEffect, useState } from "react";
import { useAuth } from "@/components/dashboard/auth";
type Meter = { meter: string; consumed: string; reserved: string; hard: number | null; soft: number | null; grace: number; warning: boolean; windowStart: string; connected: boolean };
const names: Record<string, string> = { calls: "تعداد تماس", voice_minutes: "دقیقه تماس", stt_minutes: "دقیقه تبدیل گفتار", tts_characters: "نویسه تولید صدا", llm_input_tokens: "توکن ورودی", llm_output_tokens: "توکن خروجی", embedding_tokens: "توکن embedding", storage_bytes: "حجم ذخیره‌سازی (بایت)", active_agents: "عامل فعال", tenant_users: "کاربر فعال" };
export default function QuotasPage() {
  const { apiJson, user } = useAuth(); const [data, setData] = useState<{ plan: string; meters: Meter[] } | null>(null);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let closed = false; apiJson<{ plan: string; meters: Meter[] }>("/api/v1/billing/quotas").then((result) => { if (!closed) setData(result); }).catch((e: Error) => { if (!closed) setMessage(e.message); }); return () => { closed = true; }; }, [apiJson]);
  return <section><h1 className="text-2xl font-bold">سهمیه و مصرف</h1><p role="status">{message}</p>{data && <><p className="my-3">طرح: {data.plan} — دورهٔ مصرف ماهانه بر مبنای UTC است.</p><div className="overflow-x-auto"><table className="w-full text-right"><thead><tr>{["منبع", "مصرف", "رزرو", "سقف", "مهلت اضافه", "وضعیت"].map(t => <th className="p-2" key={t}>{t}</th>)}</tr></thead><tbody>{data.meters.map(m => <tr key={m.meter} className="border-t"><td className="p-2">{names[m.meter]}</td><td>{Number(m.consumed).toLocaleString("fa-IR")}</td><td>{Number(m.reserved).toLocaleString("fa-IR")}</td><td>{m.hard == null ? "نامحدود" : m.hard.toLocaleString("fa-IR")}</td><td>{m.grace.toLocaleString("fa-IR")}</td><td>{!m.connected ? "اعمال سقف هنوز فعال نیست" : m.warning ? "بالاتر از آستانه هشدار" : "فعال"}</td></tr>)}</tbody></table></div></>}
    {user?.role === "SUPER_ADMIN" && <form className="mt-6 space-y-3 rounded border p-4" onSubmit={async e => { e.preventDefault(); const form = new FormData(e.currentTarget); const meter = String(form.get("meter")); setBusy(true); setMessage("");
      try { await apiJson("/api/v1/platform/quotas", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId: form.get("businessId"), reason: form.get("reason"), policy: { [meter]: { hard: form.get("hard") === "" ? null : Number(form.get("hard")), soft: form.get("soft") === "" ? null : Number(form.get("soft")), grace: Number(form.get("grace") || 0) } } }) }); setMessage("سهمیهٔ مستأجر ثبت شد."); setData(await apiJson("/api/v1/billing/quotas")); }
      catch (error) { setMessage(error instanceof Error ? error.message : "ثبت ناموفق"); } finally { setBusy(false); }
    }}><h2 className="font-bold">تغییر سهمیهٔ مستأجر توسط مدیر سراسری</h2><label className="block">شناسه مستأجر<input name="businessId" required className="block w-full rounded border p-2" /></label><label className="block">منبع<select name="meter" className="block rounded border p-2">{Object.entries(names).filter(([key]) => ["calls", "llm_input_tokens", "llm_output_tokens", "embedding_tokens", "tts_characters", "active_agents", "tenant_users"].includes(key)).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{[["hard", "سقف قطعی (خالی یعنی نامحدود)"], ["soft", "آستانه هشدار (اختیاری)"], ["grace", "مصرف اضافهٔ مجاز"]].map(([name, label]) => <label key={name} className="block">{label}<input name={name} type="number" min="0" step="0.0001" className="block rounded border p-2" /></label>)}<label className="block">دلیل تغییر<textarea name="reason" required minLength={10} maxLength={1000} className="block w-full rounded border p-2" /></label><button disabled={busy} className="rounded bg-slate-900 p-2 text-white">ثبت سهمیه</button></form>}
  </section>;
}
