import { beforeAll, afterAll, describe, expect, vi } from "vitest";
import { NextRequest } from "next/server";
import { eq } from "drizzle-orm";
import { db, closeDb } from "@/db";
import { billingInvoices, subscriptions, users } from "@/db/schema";
import { issueAuthTokens } from "@/lib/auth";
import { requestInvoice, recordInvoicePayment, getBilling, cancelInvoice, setSubscriptionCancellation } from "@/lib/services/billing";
import * as tenantApi from "@/app/api/v1/billing/route";
import * as platformApi from "@/app/api/v1/platform/billing/route";
import { createBusiness, createUser } from "../helpers/fixtures";
import { ensureDbReady, hasTestDatabase, itDb, truncateAll } from "../helpers/db";
const catalog = { issuer: "Synthetic Test Issuer", paymentInstructions: "Test fixture only, no real payment account", plans: [{ plan: "STARTER", amountMinor: 1234, currency: "USD" }, { plan: "BUSINESS", amountMinor: 4567, currency: "USD" }] };
const request = (token: string, method = "GET", body?: unknown) => new NextRequest("http://localhost/api/v1/billing", { method, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
async function account(platform = false, viewer = false) {
  const business = await createBusiness(); const { user } = await createUser(business.id);
  const role = platform ? "SUPER_ADMIN" : viewer ? "VIEWER" : "ADMIN";
  await db.update(users).set({ role, mfaEnabled: platform }).where(eq(users.id, user.id));
  const token = (await issueAuthTokens({ userId: user.id, businessId: business.id, role })).accessToken;
  return { business, user, token };
}
describe.skipIf(!hasTestDatabase())("manual invoice subscription lifecycle", () => {
  beforeAll(async () => { await ensureDbReady(); await truncateAll(); vi.stubEnv("BILLING_CATALOG_JSON", JSON.stringify(catalog)); });
  afterAll(async () => { vi.unstubAllEnvs(); await truncateAll(); await closeDb(); });
  itDb("isolates invoices, refuses self-settlement, and requires configured prices", async () => {
    const a = await account(), b = await account(), viewer = await account(false, true);
    expect((await tenantApi.GET(request(viewer.token))).status).toBe(403);
    const input = { plan: "STARTER", idempotencyKey: crypto.randomUUID() };
    const created = await tenantApi.POST(request(a.token, "POST", input)); expect(created.status).toBe(201);
    const invoice = await created.json();
    expect((await requestInvoice(a.business.id, input)).id).toBe(invoice.id);
    await expect(requestInvoice(a.business.id, { ...input, plan: "BUSINESS" })).rejects.toMatchObject({ status: 409 });
    expect((await getBilling(b.business.id)).invoices).toHaveLength(0);
    expect((await tenantApi.DELETE(request(b.token, "DELETE", { id: invoice.id }))).status).toBe(409);
    expect((await platformApi.GET(request(a.token))).status).toBe(403);
    expect((await platformApi.POST(request(a.token, "POST", { id: invoice.id, businessId: a.business.id, amountMinor: 1234, currency: "USD", paymentReference: "test-only-denied" }))).status).toBe(403);
    await cancelInvoice(a.business.id, invoice.id);
    await expect(cancelInvoice(a.business.id, invoice.id)).rejects.toMatchObject({ status: 409 });
    vi.stubEnv("BILLING_CATALOG_JSON", "");
    await expect(requestInvoice(b.business.id, { plan: "STARTER", idempotencyKey: crypto.randomUUID() })).rejects.toMatchObject({ status: 503 });
    vi.stubEnv("BILLING_CATALOG_JSON", JSON.stringify(catalog));
  });
  itDb("settles exactly once, rejects mismatches and reused references, and supports cancellation", async () => {
    const admin = await account(true), a = await account(), b = await account();
    const invoice = await requestInvoice(a.business.id, { plan: "STARTER", idempotencyKey: crypto.randomUUID() });
    const payment = { id: invoice.id, businessId: a.business.id, amountMinor: 1234, currency: "USD", paymentReference: "synthetic-bank-reference-01" };
    await expect(recordInvoicePayment(admin.user.id, { ...payment, amountMinor: 1233 })).rejects.toMatchObject({ status: 409 });
    await expect(recordInvoicePayment(admin.user.id, { ...payment, businessId: b.business.id })).rejects.toMatchObject({ status: 404 });
    const concurrent = await Promise.all([recordInvoicePayment(admin.user.id, payment), recordInvoicePayment(admin.user.id, payment)]);
    expect(concurrent[0]?.id).toBe(concurrent[1]?.id);
    let data = await getBilling(a.business.id); expect(data.plan).toBe("STARTER");
    const end = data.subscription!.periodEnd!;
    expect(end.getTime() - Date.now()).toBeLessThan(32 * 86400_000);
    const other = await requestInvoice(b.business.id, { plan: "STARTER", idempotencyKey: crypto.randomUUID() });
    await expect(recordInvoicePayment(admin.user.id, { ...payment, id: other.id, businessId: b.business.id })).rejects.toMatchObject({ status: 409 });
    expect((await getBilling(b.business.id)).plan).toBe("FREE");
    expect((await db.select().from(billingInvoices).where(eq(billingInvoices.id, other.id)))[0].status).toBe("open");
    await expect(requestInvoice(a.business.id, { plan: "BUSINESS", idempotencyKey: crypto.randomUUID() })).rejects.toMatchObject({ status: 409 });
    const renewal = await requestInvoice(a.business.id, { plan: "STARTER", idempotencyKey: crypto.randomUUID() });
    expect((await platformApi.GET(request(admin.token))).status).toBe(200);
    expect((await platformApi.POST(request(admin.token, "POST", { ...payment, id: renewal.id, paymentReference: "synthetic-bank-reference-02" }))).status).toBe(200);
    data = await getBilling(a.business.id); expect(data.subscription!.periodEnd!.getTime()).toBeGreaterThan(end.getTime());
    const pending = await requestInvoice(a.business.id, { plan: "STARTER", idempotencyKey: crypto.randomUUID() });
    expect((await tenantApi.PATCH(request(a.token, "PATCH", { cancelAtPeriodEnd: true }))).status).toBe(200);
    await expect(recordInvoicePayment(admin.user.id, { ...payment, id: pending.id, paymentReference: "synthetic-bank-reference-03" })).rejects.toMatchObject({ status: 409 });
    expect((await getBilling(a.business.id)).plan).toBe("STARTER");
    await expect(requestInvoice(a.business.id, { plan: "STARTER", idempotencyKey: crypto.randomUUID() })).rejects.toMatchObject({ status: 409 });
    await setSubscriptionCancellation(a.business.id, false);
    await db.update(subscriptions).set({ periodStart: new Date("2020-01-01Z"), periodEnd: new Date("2020-02-01Z") }).where(eq(subscriptions.businessId, a.business.id));
    expect((await getBilling(a.business.id)).plan).toBe("FREE");
  });
});
