import { beforeAll, afterAll, describe, expect } from "vitest";
import { NextRequest } from "next/server";
import { and, eq } from "drizzle-orm";
import { db, closeDb } from "@/db";
import { auditLogs, businesses, refreshTokens, users } from "@/db/schema";
import { issueAuthTokens, getAuthContext } from "@/lib/auth";
import { listPlatformTenants, changePlatformTenantState } from "@/lib/services/platform";
import { GET, PATCH } from "@/app/api/v1/platform/tenants/route";
import { createBusiness, createUser } from "../helpers/fixtures";
import { ensureDbReady, hasTestDatabase, itDb, truncateAll } from "../helpers/db";
const request = (token: string, body?: unknown) => new NextRequest("http://localhost/api/v1/platform/tenants", { method: body ? "PATCH" : "GET", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
describe.skipIf(!hasTestDatabase())("platform control plane", () => {
  beforeAll(async () => { await ensureDbReady(); await truncateAll(); });
  afterAll(async () => { await truncateAll(); await closeDb(); });
  itDb("denies tenant administrators and platform administrators without MFA", async () => {
    const tenant = await createBusiness(); const { user } = await createUser(tenant.id);
    const tokens = await issueAuthTokens({ userId: user.id, businessId: tenant.id, role: "ADMIN" });
    expect((await GET(request(tokens.accessToken))).status).toBe(403);
    await expect(listPlatformTenants(user.id, {})).rejects.toMatchObject({ status: 403 });
    await db.update(users).set({ role: "SUPER_ADMIN" }).where(eq(users.id, user.id));
    expect((await GET(request(tokens.accessToken))).status).toBe(403);
  });
  itDb("paginates safe tenant projections, suspends atomically, and never restores old sessions", async () => {
    const platform = await createBusiness(); const { user: admin } = await createUser(platform.id);
    await db.update(users).set({ role: "SUPER_ADMIN", mfaEnabled: true }).where(eq(users.id, admin.id));
    const token = (await issueAuthTokens({ userId: admin.id, businessId: platform.id, role: "SUPER_ADMIN" })).accessToken;
    const tenant = await createBusiness(); const { user } = await createUser(tenant.id);
    const targetToken = (await issueAuthTokens({ userId: user.id, businessId: tenant.id, role: "ADMIN" })).accessToken;
    const first = await listPlatformTenants(admin.id, { limit: 1 });
    expect(first.tenants).toHaveLength(1); expect(first.nextCursor).toBeTruthy();
    expect(first.tenants[0]).not.toHaveProperty("settings");
    const second = await listPlatformTenants(admin.id, { limit: 1, after: first.nextCursor });
    expect(second.tenants[0].id).not.toBe(first.tenants[0].id);
    const mutation = { id: tenant.id, isActive: false, reason: "Customer requested suspension" };
    expect((await PATCH(request(token, mutation))).status).toBe(200);
    expect((await db.select().from(businesses).where(eq(businesses.id, tenant.id)))[0].isActive).toBe(false);
    expect((await db.select().from(users).where(eq(users.id, user.id)))[0].credentialVersion).toBe(1);
    expect((await db.select().from(refreshTokens).where(eq(refreshTokens.userId, user.id)))[0].revokedReason).toBe("tenant_suspended");
    expect(await changePlatformTenantState(admin.id, mutation)).toMatchObject({ changed: false });
    const logs = await db.select().from(auditLogs).where(and(eq(auditLogs.businessId, tenant.id), eq(auditLogs.action, "tenant.suspended")));
    expect(logs).toHaveLength(1); expect(logs[0].metadata.reason).toBe(mutation.reason);
    await changePlatformTenantState(admin.id, { ...mutation, isActive: true });
    await expect(getAuthContext(request(targetToken))).rejects.toMatchObject({ status: 401 });
    expect((await PATCH(request(token, { ...mutation, id: platform.id }))).status).toBe(409);
    expect((await PATCH(request(token, { ...mutation, id: crypto.randomUUID() }))).status).toBe(404);
    expect((await PATCH(request(token, { ...mutation, reason: "" }))).status).toBe(400);
    await db.update(users).set({ role: "ADMIN" }).where(eq(users.id, admin.id));
    expect((await PATCH(request(token, mutation))).status).toBe(403);
  });
});
