"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/dashboard/auth";
import { PageHeader } from "@/components/dashboard/ui";
const steps=["هویت","شخصیت","دانش","ابزارها","آزمایش"];
export default function NewAgentPage(){const {apiJson}=useAuth(),router=useRouter();const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState("");const [form,setForm]=useState({name:"",language:"fa-IR",voiceId:"fa-default",systemPrompt:"",industry:"real_estate",tools:["knowledge_search","create_lead","book_appointment","transfer_call"] as string[]});
const save=async()=>{setBusy(true);setError("");try{await apiJson("/api/v1/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name,language:form.language,voiceId:form.voiceId,systemPrompt:form.systemPrompt,configuration:{industry:form.industry,tools:form.tools}})});router.push("/dashboard/agents")}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
return <div><PageHeader title="ساخت AI Agent" desc="پیکربندی مرحله‌ای منشی هوشمند"/><div className="grid gap-4 lg:grid-cols-[220px_1fr]"><aside className="saas-panel">{steps.map((s,i)=><button key={s} onClick={()=>setStep(i)} className={"mb-1 block w-full rounded-xl px-3 py-2 text-right text-sm "+(i===step?"bg-slate-900 text-white":"hover:bg-slate-50")}>{i+1}. {s}</button>)}</aside><section className="saas-panel min-h-96"><p className="saas-eyebrow">مرحله {step+1}</p><h2 className="mt-2 text-xl font-semibold">{steps[step]}</h2>{step===0&&<div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="نام Agent" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="زبان" value={form.language} onChange={v=>setForm({...form,language:v})}/><Field label="Voice" value={form.voiceId} onChange={v=>setForm({...form,voiceId:v})}/><Field label="صنعت" value={form.industry} onChange={v=>setForm({...form,industry:v})}/></div>}{step===1&&<textarea value={form.systemPrompt} onChange={e=>setForm({...form,systemPrompt:e.target.value})} className="saas-input mt-6 min-h-48 w-full" placeholder="Personality, system prompt and business rules…"/>}{step===2&&<div className="mt-6 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">پس از ذخیره، اسناد PDF/DOCX/TXT و منابع RAG را از Knowledge Manager به این workspace اضافه کنید.</div>}{step===3&&<div className="mt-6 grid gap-2 md:grid-cols-2">{["knowledge_search","search_properties","create_lead","book_appointment","transfer_call","send_message"].map(x=><label className="rounded-xl border border-slate-200 p-3 text-sm" key={x}><input type="checkbox" checked={form.tools.includes(x)} onChange={e=>setForm({...form,tools:e.target.checked?[...form.tools,x]:form.tools.filter(t=>t!==x)})} className="ml-2"/>{x}</label>)}</div>}{step===4&&<div className="mt-6 rounded-xl bg-slate-950 p-5 text-sm text-slate-200"><p>Agent: {form.name||"بدون نام"}</p><p>Language: {form.language}</p><p>Voice: {form.voiceId}</p><p>Tools: {form.tools.join(", ")}</p></div>}{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-8 flex justify-end gap-2"><button className="saas-secondary" disabled={step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>قبلی</button>{step<4?<button className="saas-primary" onClick={()=>setStep(x=>Math.min(4,x+1))}>بعدی</button>:<button disabled={busy||!form.name.trim()} className="saas-primary disabled:opacity-50" onClick={save}>{busy?"در حال ذخیره…":"ذخیره Agent"}</button>}</div></section></div></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm"><span className="mb-2 block text-slate-600">{label}</span><input className="saas-input w-full" value={value} onChange={e=>onChange(e.target.value)}/></label>}