"use client";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/dashboard/auth";
type Pipeline = { id: string; name: string; stages: string[] };
type Deal = { id: string; title: string; stage: string; value: string; currency: string; pipelineId: string };
type Task = { id: string; title: string; dueAt: string | null; status: string };
export default function CrmPage() {
  const { apiJson } = useAuth(); const [pipelines, setPipelines] = useState<Pipeline[]>([]); const [deals, setDeals] = useState<Deal[]>([]); const [tasks, setTasks] = useState<Task[]>([]);
  const [title, setTitle] = useState(""); const [value, setValue] = useState("0"); const [pipelineId, setPipelineId] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [due, setDue] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(() => Promise.all([apiJson<{ data: Pipeline[] }>("/api/v1/crm/pipelines"), apiJson<{ data: Deal[] }>("/api/v1/crm/opportunities"), apiJson<{ data: Task[] }>("/api/v1/crm/tasks")]), [apiJson]);
  useEffect(() => { load().then(([p, d, t]) => { setPipelines(p.data); setDeals(d.data); setTasks(t.data); }).catch((e: Error) => setMessage(e.message)); }, [load]);
  async function mutate(entity: string, data: unknown, method = "POST") { try { await apiJson(`/api/v1/crm/${entity}`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const [p, d, t] = await load(); setPipelines(p.data); setDeals(d.data); setTasks(t.data); setMessage("ذخیره شد."); } catch (error) { setMessage((error as Error).message); } }
  const pipeline = pipelines.find((p) => p.id === pipelineId) ?? pipelines[0];
  return <div className="space-y-5"><h1 className="text-2xl font-bold">فرصت‌ها و پیگیری‌ها</h1><p role="status">{message}</p>
    {!pipelines.length && <button className="rounded border bg-white p-3" onClick={() => void mutate("pipelines", { name: "فروش", stages: ["جدید", "بررسی", "پیشنهاد", "موفق", "ناموفق"] })}>ایجاد مسیر فروش</button>}
    <form className="flex flex-wrap gap-3 rounded-xl border bg-white p-4" onSubmit={(e) => { e.preventDefault(); if (pipeline) void mutate("opportunities", { title, value, pipelineId: pipeline.id, stage: pipeline.stages[0] }); }}><label>عنوان فرصت<input required value={title} onChange={(e) => setTitle(e.target.value)} className="m-2 rounded border p-2" /></label><label>ارزش (تومان)<input required inputMode="decimal" value={value} onChange={(e) => setValue(e.target.value)} className="m-2 rounded border p-2" /></label><label>مسیر<select value={pipeline?.id ?? ""} onChange={(e) => setPipelineId(e.target.value)} className="m-2 rounded border p-2">{pipelines.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button disabled={!pipeline} className="rounded bg-slate-900 p-2 text-white">ثبت فرصت</button></form>
    <div className="grid gap-3 md:grid-cols-3">{pipeline?.stages.map((stage) => <section key={stage} className="rounded-xl bg-slate-100 p-3"><h2 className="mb-3 font-bold">{stage}</h2>{deals.filter((d) => d.pipelineId === pipeline.id && d.stage === stage).map((d) => <article key={d.id} className="mb-3 space-y-2 rounded-lg border bg-white p-3"><h3>{d.title}</h3><p>{Number(d.value).toLocaleString("fa-IR")} {d.currency}</p><label className="text-sm">تغییر مرحله<select aria-label={`مرحله ${d.title}`} value={d.stage} onChange={(e) => void mutate("opportunities", { id: d.id, stage: e.target.value }, "PATCH")} className="mx-2 rounded border p-1">{pipeline.stages.map((s) => <option key={s}>{s}</option>)}</select></label></article>)}</section>)}</div>
    <section className="rounded-xl border bg-white p-4"><h2 className="mb-3 text-xl font-bold">وظایف پیگیری</h2><form className="flex flex-wrap gap-3" onSubmit={(e) => { e.preventDefault(); void mutate("tasks", { title: taskTitle, dueAt: due ? new Date(due).toISOString() : null }); }}><label>عنوان<input required value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} className="m-2 rounded border p-2" /></label><label>موعد<input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} className="m-2 rounded border p-2" /></label><button className="rounded border p-2">ثبت وظیفه</button></form>{tasks.map((t) => <div key={t.id} className="mt-3 flex flex-wrap items-center justify-between border-t py-3"><p>{t.title} · {t.dueAt ? new Date(t.dueAt).toLocaleString("fa-IR") : "بدون موعد"}</p><select aria-label={`وضعیت ${t.title}`} value={t.status} onChange={(e) => void mutate("tasks", { id: t.id, status: e.target.value }, "PATCH")} className="rounded border p-2"><option value="OPEN">باز</option><option value="DONE">انجام‌شده</option><option value="CANCELLED">لغوشده</option></select></div>)}</section>
  </div>;
}
